spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xiaoyu
    # useAffectedRows=true ：参数设为 true，表示操作数据库时返回的为影响的行数，否则mybatis返回的是匹配的行数
    url: jdbc:mysql://localhost/hrm_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
  redis:
    host: 192.168.25.25
    port: 6379
    password: xiaoyu
    timeout: 10
  # 指定生产环境
#  profiles:
#    active: prod
server:
  port: 8081
# 配置 开启驼峰命名的方法
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# 存储在redis中的用户信息 key 前缀
XIAOYU_USER: user_inf

# 文件上传路径
FILE_PATH: C:/Users/Yuqiang/IdeaProjects/xiaoyu-hrm/uploads/

# 指定日志的路径
logging:
  file:
    path: logs


